### PR TITLE
edit page backend

### PR DESCRIPTION
**Pull request by adileep7**
updating values in the backend

### CODE REVIEW

**Comment by N3ROO** [comment]
I can't see what changed because most of the changes were made on an other branch

**Comment by adileep7** [comment]
> I can't see what changed because most of the changes were made on an other branch

I made some changes in server.py. So, this branch isn't the same as edit-post.

**Comment by N3ROO** [comment]
Oh yeah okay! Sorry I could not see what actually changed, there was so much change. I think that we can merge (and we should)

**Comment by adileep7** [comment]
> Oh yeah okay! Sorry I could not see what actually changed, there was so much change. I think that we can merge (and we should)

ok cool :) I can resolve conflicts and merge now right? Or do I have to wait for another review?

**Pull request merged**
